trigger:
  - master

pr:
  branches:
    include:
    - master

jobs:
  - job: Windows
    timeoutInMinutes: 240
    pool:
      vmImage: windows-latest

    steps:
      - powershell: .\main.ps1
        displayName: Run `main.ps1`
  
  - job: Linux
    timeoutInMinutes: 240
    pool:
      vmImage: ubuntu-latest
    variables:
    - name: 'CI'
      value: true

    steps:
      - bash: |
          sudo apt purge ruby -y
          sudo apt purge openjdk* -y
          sudo apt purge msodbcsql17 -y
          sudo apt purge gcc -y
          sudo apt autoremove -y
        displayName: Clean system.

      - bash: |
          sudo chmod +x ./main.sh
          ./main.sh
        displayName: Run `main.sh`