name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # every sunday 10 pm
    - cron:  '0 22 * * 0'

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/actions/runner-images/issues/910
      - name: install winget
        run: |
          Install-Module NtObjectManager -Force
          $vclibs = Invoke-WebRequest -Uri "https://store.rg-adguard.net/api/GetFiles" -Method "POST" -ContentType "application/x-www-form-urlencoded" -Body "type=PackageFamilyName&url=Microsoft.VCLibs.140.00_8wekyb3d8bbwe&ring=RP&lang=en-US" -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match "Microsoft.VCLibs.140.00_.+_x64__8wekyb3d8bbwe.appx" | Foreach-Object href
          $vclibsuwp = Invoke-WebRequest -Uri "https://store.rg-adguard.net/api/GetFiles" -Method "POST" -ContentType "application/x-www-form-urlencoded" -Body "type=PackageFamilyName&url=Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe&ring=RP&lang=en-US" -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match "Microsoft.VCLibs.140.00.UWPDesktop_.+_x64__8wekyb3d8bbwe.appx" | Foreach-Object href
          Invoke-WebRequest $vclibsuwp -OutFile Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe.appx
          Invoke-WebRequest $vclibs -OutFile Microsoft.VCLibs.140.00_8wekyb3d8bbwe.appx
          Add-AppxPackage -Path .\Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe.appx
          Add-AppxPackage -Path .\Microsoft.VCLibs.140.00_8wekyb3d8bbwe.appx

          Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
          Register-PackageSource -provider NuGet -name nugetRepository -location https://www.nuget.org/api/v2
          Install-Package Microsoft.UI.Xaml -Force

          Invoke-WebRequest 'https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' -OutFile winget.msixbundle
          Add-AppxPackage -Path .\winget.msixbundle
        shell: powershell

      - run: winget --info

      - name: run `main.ps1`
        run: .\main.ps1
        shell: powershell

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: clean system
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          sudo apt purge ruby* -y
          sudo apt purge openjdk* -y
          sudo apt purge msodbcsql17 -y
          sudo apt purge gcc -y
          sudo apt autoremove -y
        shell: bash

      - name: run `main.sh`
        run: |
          sudo chmod +x ./main.sh
          ./main.sh
        shell: bash
