name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # every sunday 10 pm
    - cron:  '0 22 * * 0'

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: install winget
        run: |
          Invoke-WebRequest 'https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' -OutFile $env:TEMP\winget.msixbundle
          Invoke-WebRequest 'https://github.com/microsoft/winget-cli/releases/download/v1.1.12653/9c0fe2ce7f8e410eb4a8f417de74517e_License1.xml' -Outfile $env:TEMP\winget.license

          Add-AppxProvisionedPackage -Online -PackagePath $env:TEMP\winget.msixbundle -LicensePath $env:TEMP\winget.license
        shell: powershell

      - run: winget --info

      - name: run `main.ps1`
        run: .\main.ps1
        shell: powershell

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: clean system
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          sudo apt purge ruby* -y
          sudo apt purge openjdk* -y
          sudo apt purge msodbcsql17 -y
          sudo apt purge gcc -y
          sudo apt autoremove -y
        shell: bash

      - name: run `main.sh`
        run: |
          sudo chmod +x ./main.sh
          ./main.sh
        shell: bash
